ERROR_CODE = {
    "100": "Success",
    "101": "File Not Found",
    "102": "Name Not Matched And Account not Matched",
    "103": "Partial Name Match",
    "104": "Password Not Matched",
    "105": "File Not Reasable",
    "106": "Two Files Match",
    "107": "Insufficient Duration",
    "108": "XpressId Not Found",
    "109": "Two Request Id Same",
    "110": "Bank Name Invalid",
    "111": "Wrong File Format",
    "112": "Account Not Match And Name Matched",
    "113": "TaskId Not Found",
    "114": "File Name Paramerter Missing",
    "115": "TaskId Parameter Missing",
    "116": "XpressId Parameter Missing",
    "117": "Error Storing Parameters",
    "118": "Account Match And Name Not Matched",
    "119": "Extractor Not Available",
    "120": "TaskId And xpressId combination not Found",
    "121": "Request Id not Found",
    "201": "Format Not Matched",
    "202": "Account Not Match And Partial Name Matched",
    "203": "pdf Overlapping",
    "204": "Full pdfOver Lapped",
    "205": "User Not Found"
}
